<a href="https://colab.research.google.com/github/24f3005028/MLP-ASSIGNMENTS/blob/main/MLP_Prac_oppe_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MLP PRAC OPPE 4**

In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv("/content/Copy of V1 (pre) (1).csv")

In [17]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,IncomeGroup
0,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
1,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
2,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
3,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
4,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K

## Q2. How many total number of rows and columns are there in the dataset?
- Rows:2000 , Columns: 15
- Rows:20000 , Columns: 14
- Rows:20000 , Columns: 16
- Rows:20000 , Columns: 15

In [18]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,IncomeGroup
0,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
1,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
2,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
3,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
4,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,26,Private,62438,Bachelors,13,Married-civ-spouse,Sales,Wife,White,Female,0,0,40,United-States,>50K
19996,62,Private,57970,7th-8th,4,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
19997,31,Private,137290,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,55,United-States,>50K
19998,25,Private,29020,Assoc-acdm,12,Divorced,Adm-clerical,Not-in-family,Black,Female,0,0,45,United-States,<=50K
19999,55,Private,256953,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,Black,Female,0,0,44,United-States,<=50K

ans 20000 rows × 15 columns

## Q3. Is there any Missing values in the given dataset ?
- Yes
- No

In [19]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
IncomeGroup       0
dtype: int64

ans no

## Q4. Check all " ?" symbol in the dataset and replace it with "np.nan" value . Which of the columns in the dataset have null values?
- age
- native-country
- capital-gain
- workclass
- occupation
- None of these

\


Answer: B, D, E

In [20]:
df["age"] = df["age"].replace(" ?",np.nan)
df["native-country"] = df["native-country"].replace(" ?",np.nan)
df["capital-gain"] = df["capital-gain"].replace(" ?",np.nan)
df["workclass"] = df["workclass"].replace(" ?",np.nan)
df["occupation"] = df["occupation"].replace(" ?",np.nan)

In [21]:
df.isnull().sum()

age                  0
workclass         1137
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1140
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     354
IncomeGroup          0
dtype: int64

## Q5. What fraction of total samples (in percentage) have missing value in occupation column?

\
Answer: 5.7%

In [22]:
occ = df["occupation"].isnull().sum()

total = df["occupation"].size
frac = occ/total
perc = frac*100
print(perc)

5.7

## Q6. What fraction of total samples(In percentage) have income <= 50k in the given dataset? (round the value upto 2 decimal places)
- 75.95
- 75.83
- 76.51
- 72.82
- 76.00

\

Answer: C

In [23]:
inc = df["IncomeGroup"].value_counts("<=50K")
total = df["IncomeGroup"].size
perc = (inc*100)/100
print(perc)

IncomeGroup
<=50K    0.7651
>50K     0.2349
Name: proportion, dtype: float64

## Q7: What is the mean age of the samples given in the dataset(mark the closest integer from the given options)?
- 25
- 34
- 38
- 45
- 50

\

Answer: C

In [24]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,20000.000000,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000
mean,38.553000,1.903596e+05,10.063500,1084.616350,88.035300,40.474300
std,13.635369,1.056593e+05,2.583602,7487.246198,403.624064,12.347893
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.186750e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.784735e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376982e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

## Q8: How many people have completed their education upto "Preschool" only ?
- 29
- 32
- 26
- 27

\

Answer: B

In [25]:
num = df["education"].value_counts()
print(num)

education
HS-grad         6477
Some-college    4458
Bachelors       3279
Masters         1039
Assoc-voc        826
11th             718
Assoc-acdm       662
10th             579
7th-8th          403
Prof-school      353
9th              322
12th             270
Doctorate        257
5th-6th          223
1st-4th          102
Preschool         32
Name: count, dtype: int64

## Q9. What is the correlation cofficient between column "education-num" and column "capital-gain" ?

\

Answer: 0.12

In [26]:
corr_value = df["education-num"].corr(df["capital-gain"])
print(corr_value)

0.12456727883397226

## Apply SimpleImputer with strategy = 'most_frequent' to replace all NaN value by mode of respective column in the original dataset.(Use this updated dataset only for all further questions)

## Q10. What is the mode of 'occupation' column of updated datset?
- Adm-clerical
- Prof-specialty
- Exec-managerial
- Craft-repair
- Private

\

Answer: B

In [27]:
l=df.columns.to_list()
l

['age',
 'workclass',
 'fnlwgt',
 'education',
 'education-num',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'native-country',
 'IncomeGroup']

In [28]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline


si=SimpleImputer(strategy="most_frequent")

pipe = Pipeline(
    [("imputer",si)]
).set_output(transform="pandas")

df[l]=pipe.fit_transform(df[l])

In [29]:
df["occupation"].mode()

0     Prof-specialty
Name: occupation, dtype: object

## Split the dataset into X1, X2 and y, where X1 contains all Numerical features, X2 contains all categorical features(except "IncomeGroup") and save 'IncomeGroup' column in y variable. Then apply OneHotEncoder on the categorical features(X2) with option (sparse = False) and StandardScaler on the numerical features (X2).


## Q11. What is the total number of columns in X1 and X2 variables respectively?
- (6,9)
- (9,6)
- (6,8)
- (8,6)

\

Answer: C

In [35]:
df.dtypes

age               object
workclass         object
fnlwgt            object
education         object
education-num     object
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain      object
capital-loss      object
hours-per-week    object
native-country    object
IncomeGroup       object
dtype: object

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             20000 non-null  object
 1   workclass       20000 non-null  object
 2   fnlwgt          20000 non-null  object
 3   education       20000 non-null  object
 4   education-num   20000 non-null  object
 5   marital-status  20000 non-null  object
 6   occupation      20000 non-null  object
 7   relationship    20000 non-null  object
 8   race            20000 non-null  object
 9   sex             20000 non-null  object
 10  capital-gain    20000 non-null  object
 11  capital-loss    20000 non-null  object
 12  hours-per-week  20000 non-null  object
 13  native-country  20000 non-null  object
 14  IncomeGroup     20000 non-null  object
dtypes: object(15)
memory usage: 2.3+ MB

In [36]:
num_cols = ["age",	"fnlwgt",	"education-num",	"capital-gain"	,"capital-loss"	,"hours-per-week"]
Y = df["IncomeGroup"]
X = df.drop(columns=["IncomeGroup"])

cat_cols = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country"
]
X1 = X[num_cols]
X2 = X[cat_cols]
print("X1 shape:", X1.shape)

print("X2 shape:", X2.shape)

X1 shape: (20000, 6)
X2 shape: (20000, 8)

In [39]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y = le.fit_transform(Y)
print(Y)

[0 0 1 ... 1 0 0]

## Apply StandardScaler on the X1 data and OneHotEncoder on X2 data with option (sparse = False).

## Q12. What are the data types of X1 and X2?
- dataframe, dataframe
- dataframe, numpy array
- dense scipy array, numpy array
- numpy array, numpy array

\

Answer: D

In [45]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
oh = OneHotEncoder(sparse_output=False)
ss = StandardScaler()
X1= ss.fit_transform(X1)
X2=oh.fit_transform(X2)

In [47]:
type(X1)
type(X2)

numpy.ndarray

## Concatenate X1 and X2 and call it X( Keep axis = 1) and then Convert X to a dataframe.
## Q13. What is the new shape of resultant X?

- (20000, 105)
- (20000, 204)
- (20000, 14)
- (2000, 98)

\

Answer: A

In [48]:
X= np.concatenate((X1,X2),axis=1)
X=pd.DataFrame(X)
X

,0,1,2,3,4,5,6,7,8,9,...,95,96,97,98,99,100,101,102,103,104
0,1.719615,-1.546978,-2.346975,-0.144865,-0.218118,2.067263,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,-1.507368,0.167934,-1.185777,-0.144865,-0.218118,-1.253225,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,-0.993984,-0.831785,1.136620,3.571948,-0.218118,0.771463,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,-0.407260,3.039631,-0.411645,-0.144865,-0.218118,-0.038412,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-0.187238,0.967382,-1.185777,-0.144865,-0.218118,-0.038412,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,-0.920644,-1.210729,1.136620,-0.144865,-0.218118,-0.038412,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19996,1.719615,-1.253017,-2.346975,-0.144865,-0.218118,-0.038412,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19997,-0.553941,-0.502283,1.136620,-0.144865,-0.218118,1.176400,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19998,-0.993984,-1.527017,0.749554,-0.144865,-0.218118,0.366525,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19999,1.206231,0.630281,-0.411645,-0.144865,-0.218118,0.285538,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

# Model Building

Make use of your preprocessed data that you got from above preprocessing steps.

Note: In current OPPE setup you will be given the preprocessed dataset for Model Building.

## Q14. Split the dataset into training and validation dataset into 80:20 ratio while keeping random_state =64. what is the shape of the y_train dataset?
- (20000,)
- (16000, 15)
- (20000, 14)
- (4000, 98)
- (16000,)


\

Answer: D

## Instantiate a perceptron classifier that with following parameters:
- Fit the intercept
- Put warm start to be False

## Fit this perceptron model with the training dataset and calculate the accuracy score for training data.
## Q15: Which of the following option matches with the score?
- 0.8130625
- 0.8379375
- 0.8239375
- 0.8058125
- 0.78475


\

Answer: A

## Q16. Create a new Perceptron(random_state=42) object with given settings in the instrunctions and train it on training set . What is the value of bias (intercept) (upto 1 decimal point) ?
- Set early stopping and fit intercept to be True
- Put warm start to be False


\

Answer: -8

## Use SGDClassifier on the training dataset (X_train and y_train) to train the model. Use the following parameters:

- log is the loss function to be used
- apply ridge regularization,
- maximum number of passes over the training data is 10
- initial learning rate is 0.01,
- regularization rate value is 0.001,
- learning rate should not change during training.
- Take random_state=64.
- Set warm_state as False

Note : Please ignore the convergence warning.

## Q17. Based on this operation, calculate and enter the correct value of accuracy (Upto 4 decimal points).

ANS: (Type: Range) 0.840,0.855

## Take LogisticRegression estimator with following parameters for fitting on the training dataset:
- Use sag as solver
- Set random state to be equal to 64
- Tolerance for stopping criteria to be 1e-3
- Maximum number of iterations taken for the solvers to converge to be 100

##Q18. Enter the recall score you got for the given model (Take average as macro).

ANS: (Type: Range) 0.74,0.78

## Use Gridsearchcv with KNeighborsClassifier() being the estimator, accuracy as scoring parameter, cv value as 4 and consider [1,3,5,7] as "number of neighbors" to be examined.

## Consider following parameters for KNeighborsClassifier():
- Take metric as 'minkowski',
- Set P value as 2
- Keep other parameter values as default value.

## Q19. What is the best value of K you obtained using above instruction?


\

Answer: 7

#(Common Instruction for Q20 to Q23)
## Take DecisionTreeClassifier(random_state = 64) with GridSearchCV to train the model.Hyperparameter tuning to be done over the following parameters:
- Use criterion as 'entropy' or 'gini'
- Use splitter as 'random' or 'best'
- Use minimum number of samples per leaf as [2,4,6,8,10]
- Use maximum depth as [3,4,5,6]
- Use cross validation = 4

## Q20. Enter the value (up to 2 decimal points) of the 'score' on testing set using best model.


\

Answer: 0.84

## Q21. Enter the value of best max_depth of the model after training with GridSearchCV.


\

Answer: 6

## Q22. Enter the value of best min_samples_leaf of the model after training with GridSearchCV.


\

Answer: 10

## Q23: What are the number of nodes in the optimal tree?


\

Answer: 75

## Take RandomForestClassifier (random state to be 64) with GridSearchCV to tune the number of decision trees with training set. The number of trees in forest can range from 5 to 10 (both inclusive).
## Q24. Mark the number of decision trees that will produce the best score on the training data.
- 5
- 7
- 8
- 10
- 9
- 6


\

Answer: D

# (Common Instructions for Q25,Q26)

## Take an adaboost model with following hyperparameter values and tune it using GridsearchCV.
- Use n_estimators as [10,20,30]
- random_state = 64
- Use learning_rate as [0.5,1,2]
- Take cv value= 4

## Q25. Train the 'model' using above instructions and enter the 'accuracy score' (up to 3 decimal points) on the test data.


\

Answer: 0.85

## Q26. Enter the value of best n_estimators of the model after training with GridSearchCV.


\

Answer: 30

## Apply GridsearchCV and support vector machine (SVM)(kernel':('linear', 'rbf'), 'C':[1, 10]) on the training dataset X_train, y_train and calculate the best value of C and kernel.

## Q27. Which of the following options represent the best parameters. (Keep patience: It is common if it takes arround 5 min to complete the run.)

- {'C': 1, 'kernel': 'rbf'}
- {'C': 10, 'kernel': 'rbf'}
- {'C': 10, 'kernel': 'linear'}
- {'C': 1, 'kernel': 'linear'}
- None of these

\

Answer: A